nopCommerce_4.40.3_Source/src/Presentation/Nop.Web/Areas/Admin/Controllers/ReviewTypeController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Catalog;
using Nop.Services.Catalog;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// Represent a review type controller
    /// </summary>
    public partial class ReviewTypeController : BaseAdminController
    {
        #region Fields

        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IReviewTypeModelFactory _reviewTypeModelFactory;
        private readonly IReviewTypeService _reviewTypeService;

        #endregion

        #region Ctor

        public ReviewTypeController(ICustomerActivityService customerActivityService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IReviewTypeModelFactory reviewTypeModelFactory,
            IReviewTypeService reviewTypeService)
        {
            _reviewTypeModelFactory = reviewTypeModelFactory;
            _reviewTypeService = reviewTypeService;
            _customerActivityService = customerActivityService;
            _localizedEntityService = localizedEntityService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
        }

        #endregion

        #region Utilities

        /// <returns>A task that represents the asynchronous operation</returns>
        protected virtual async Task UpdateReviewTypeLocalesAsync(ReviewType reviewType, ReviewTypeModel model)
        {
            foreach (var localized in model.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(reviewType,
                    x => x.Name,                    
                    localized.Name,
                    localized.LanguageId);

                await _localizedEntityService.SaveLocalizedValueAsync(reviewType,
                   x => x.Description,
                   localized.Description,
                   localized.LanguageId);
            }
        }

        #endregion

        #region Review type

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual async Task<IActionResult> List()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //select an appropriate card
            SaveSelectedCardName("catalogsettings-review-types");

            //we just redirect a user to the catalog settings page
            return RedirectToAction("Catalog", "Setting");
        }

        [HttpPost]
        public virtual async Task<IActionResult> List(ReviewTypeSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return await AccessDeniedDataTablesJson();

            //prepare model
            var model = await _reviewTypeModelFactory.PrepareReviewTypeListModelAsync(searchModel);

            return Json(model);
        }

        public virtual async Task<IActionResult> Create()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //prepare model
            var model = await _reviewTypeModelFactory.PrepareReviewTypeModelAsync(new ReviewTypeModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual async Task<IActionResult> Create(ReviewTypeModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var reviewType = model.ToEntity<ReviewType>();
                await _reviewTypeService.InsertReviewTypeAsync(reviewType);                

                //activity log
                await _customerActivityService.InsertActivityAsync("AddNewReviewType",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.AddNewReviewType"), reviewType.Id), reviewType);

                //locales                
                await UpdateReviewTypeLocalesAsync(reviewType, model);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Settings.ReviewType.Added"));

                return continueEditing ? RedirectToAction("Edit", new { id = reviewType.Id }) : RedirectToAction("List");                
            }

            //prepare model
            model = await _reviewTypeModelFactory.PrepareReviewTypeModelAsync(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        public virtual async Task<IActionResult> Edit(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //try to get an product review type with the specified id
            var reviewType = await _reviewTypeService.GetReviewTypeByIdAsync(id);
            if (reviewType == null)
                return RedirectToAction("List");

            //prepare model
            var model = await _reviewTypeModelFactory.PrepareReviewTypeModelAsync(null, reviewType);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual async Task<IActionResult> Edit(ReviewTypeModel model, bool continueEditing)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //try to get an review type with the specified id
            var reviewType = await _reviewTypeService.GetReviewTypeByIdAsync(model.Id);
            if (reviewType == null)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                reviewType = model.ToEntity(reviewType);
                await _reviewTypeService.UpdateReviewTypeAsync(reviewType);

                //activity log
                await _customerActivityService.InsertActivityAsync("EditReviewType",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.EditReviewType"), reviewType.Id),
                    reviewType);

                //locales
                await UpdateReviewTypeLocalesAsync(reviewType, model);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Settings.ReviewType.Updated"));

                return continueEditing ? RedirectToAction("Edit", new { id = reviewType.Id }) : RedirectToAction("List");                
            }

            //prepare model
            model = await _reviewTypeModelFactory.PrepareReviewTypeModelAsync(model, reviewType, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> Delete(int id)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //try to get an review type with the specified id
            var reviewType = await _reviewTypeService.GetReviewTypeByIdAsync(id);
            if (reviewType == null)
                return RedirectToAction("List");

            try
            {
                await _reviewTypeService.DeleteReviewTypeAsync(reviewType);

                //activity log
                await _customerActivityService.InsertActivityAsync("DeleteReviewType",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.DeleteReviewType"), reviewType),
                    reviewType);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Settings.ReviewType.Deleted"));

                return RedirectToAction("List");
            }
            catch (Exception exc)
            {
                await _notificationService.ErrorNotificationAsync(exc);
                return RedirectToAction("Edit", new { id = reviewType.Id });
            }            
        }

        #endregion
    }
}

nopCommerce_4.40.3_Source/src/Presentation/Nop.Web/Areas/Admin/Views/ReviewType/Create.cshtml
@model ReviewTypeModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Settings.ReviewType.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Catalog settings");
}

<form asp-controller="ReviewType" asp-action="Create" method="post" id="reviewtype-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Settings.ReviewType.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Settings.ReviewType.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductReviewTypeButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

nopCommerce_4.40.3_Source/src/Presentation/Nop.Web/Areas/Admin/Views/ReviewType/Edit.cshtml
@model ReviewTypeModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Settings.ReviewType.EditDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Catalog settings");
}

<form asp-controller="ReviewType" asp-action="Edit" method="post" id="reviewtype-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Settings.ReviewType.EditDetails") - @Model.Name
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Settings.ReviewType.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="reviewtype-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductReviewTypeButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="reviewtype-delete" />

nopCommerce_4.40.3_Source/src/Presentation/Nop.Web/Areas/Admin/Views/ReviewType/List.cshtml
@model ReviewTypeSearchModel

<div class="card-body">
    <p>
        @T("Admin.Settings.ReviewType.Description")
        <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.ProductReviews", Docs.ProductReviews + Utm.OnAdmin)" asp-add-wrapper="false"/>
    </p>
    @await Html.PartialAsync("Table", new DataTablesModel
    {
        Name = "reviewtypes-grid",
        UrlRead = new DataUrl("List", "ReviewType", null),
        Length = Model.PageSize,
        LengthMenu = Model.AvailablePageSizes,
        ColumnCollection = new List<ColumnProperty>
        {
            new ColumnProperty(nameof(ReviewTypeModel.Name))
            {
                Title = T("Admin.Settings.ReviewType.Fields.Name").Text,
                Width = "300"
            },
            new ColumnProperty(nameof(ReviewTypeModel.IsRequired))
            {
                Title = T("Admin.Settings.ReviewType.Fields.IsRequired").Text,
                Width = "100",
                ClassName = NopColumnClassDefaults.CenterAll,
                Render = new RenderBoolean()
            },
            new ColumnProperty(nameof(ReviewTypeModel.VisibleToAllCustomers))
            {
                Title = T("Admin.Settings.ReviewType.Fields.VisibleToAllCustomers").Text,
                Width = "100",
                ClassName = NopColumnClassDefaults.CenterAll,
                Render = new RenderBoolean()
            },
            new ColumnProperty(nameof(ReviewTypeModel.DisplayOrder))
            {
                Title = T("Admin.Settings.ReviewType.Fields.DisplayOrder").Text,
                Width = "100",
                ClassName = NopColumnClassDefaults.CenterAll
            },
            new ColumnProperty(nameof(ReviewTypeModel.Id))
            {
                Title = T("Admin.Common.Edit").Text,
                Width = "100",
                ClassName =  NopColumnClassDefaults.Button,
                Render = new RenderButtonEdit(new DataUrl("~/Admin/ReviewType/Edit/"))
            }
        }
    })
</div>    
<div class="card-footer">
    <a class="btn btn-primary" href="@Url.Action("Create", "ReviewType")">
        <i class="fas fa-plus-square"></i>
        @T("Admin.Common.AddNew")
    </a>
</div>

nopCommerce_4.40.3_Source/src/Presentation/Nop.Web/Areas/Admin/Views/ReviewType/_CreateOrUpdate.cshtml
@model ReviewTypeModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="cards-group">
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductReviewTypeTop, additionalData = Model })
                <div class="card card-default">
                    <div class="card-body">
                        @(await Html.LocalizedEditorAsync<ReviewTypeModel, ReviewTypeLocalizedModel>("review-type-localized",
                                @<div>
                                    <div class="form-group row">
                                        <div class="col-md-3">
                                            <nop-label asp-for="@Model.Locales[item].Name" />
                                        </div>
                                        <div class="col-md-9">
                                            <nop-editor asp-for="@Model.Locales[item].Name" />
                                            <span asp-validation-for="@Model.Locales[item].Name"></span>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-3">
                                            <nop-label asp-for="@Model.Locales[item].Description" />
                                        </div>
                                        <div class="col-md-9">
                                            <nop-editor asp-for="@Model.Locales[item].Description" asp-template="RichEditor" />
                                            <span asp-validation-for="@Model.Locales[item].Description"></span>
                                        </div>
                                    </div>
                                    <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
                                </div>
      ,
                                                @<div>
                                                    <div class="form-group row">
                                                        <div class="col-md-3">
                                                            <nop-label asp-for="Name" />
                                                        </div>
                                                        <div class="col-md-9">
                                                            <nop-editor asp-for="Name" asp-required="true" />
                                                            <span asp-validation-for="Name"></span>
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <div class="col-md-3">
                                                            <nop-label asp-for="Description" />
                                                        </div>
                                                        <div class="col-md-9">
                                                            <nop-editor asp-for="Description" asp-required="true" asp-template="RichEditor" />
                                                            <span asp-validation-for="Description"></span>
                                                        </div>
                                                    </div>
                                                </div>
                      ))
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="DisplayOrder" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="DisplayOrder" />
                                <span asp-validation-for="DisplayOrder"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="IsRequired" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="IsRequired" />
                                <span asp-validation-for="IsRequired"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="VisibleToAllCustomers" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="VisibleToAllCustomers" />
                                <span asp-validation-for="VisibleToAllCustomers"></span>
                            </div>
                        </div>
                    </div>
                </div>
                @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ProductReviewTypeBottom, additionalData = Model })
            </div>
        </div>
    </div>
</section>