nopCommerce_4.40.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Models/Tax/TaxCategoryListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Tax.Avalara.Models.Tax
{
    /// <summary>
    /// Represents a tax category list model
    /// </summary>
    public record TaxCategoryListModel : BasePagedListModel<TaxCategoryModel>
    {
    }
}

nopCommerce_4.40.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Models/Tax/TaxCategoryModel.cs
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Tax.Avalara.Models.Tax
{
    /// <summary>
    /// Represents an extended tax category model
    /// </summary>
    public record TaxCategoryModel : Nop.Web.Areas.Admin.Models.Tax.TaxCategoryModel
    {
        #region Properties

        public string Description { get; set; }

        [NopResourceDisplayName("Plugins.Tax.Avalara.Fields.TaxCodeType")]
        public string TypeId { get; set; }
        public string Type { get; set; }

        #endregion
    }
}

nopCommerce_4.40.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Models/Tax/TaxCategorySearchModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Tax.Avalara.Models.Tax
{
    /// <summary>
    /// Represents a tax category search model
    /// </summary>
    public record TaxCategorySearchModel : BaseSearchModel
    {
        #region Ctor

        public TaxCategorySearchModel()
        {
            AddTaxCategory = new TaxCategoryModel();
            AvailableTypes = new List<SelectListItem>();
        }

        #endregion

        #region Properties

        public TaxCategoryModel AddTaxCategory { get; set; }

        public IList<SelectListItem> AvailableTypes { get; set; }

        #endregion
    }
}

nopCommerce_4.40.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Controllers/AvalaraTaxController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Tax;
using Nop.Plugin.Tax.Avalara.Services;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Services.Tax;
using Nop.Web.Areas.Admin.Controllers;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Tax;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Models.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Tax.Avalara.Controllers
{
    public class AvalaraTaxController : TaxController
    {
        #region Fields

        private readonly AvalaraTaxManager _avalaraTaxManager;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IStaticCacheManager _cacheManager;
        private readonly ITaxCategoryService _taxCategoryService;
        private readonly ITaxPluginManager _taxPluginManager;

        #endregion

        #region Ctor

        public AvalaraTaxController(AvalaraTaxManager avalaraTaxManager,
            IGenericAttributeService genericAttributeService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStaticCacheManager cacheManager,
            ITaxCategoryService taxCategoryService,
            ITaxModelFactory taxModelFactory,
            ITaxPluginManager taxPluginManager,
            IWorkContext workContext,
            TaxSettings taxSettings) : base(permissionService,
                settingService,
                taxCategoryService,
                genericAttributeService,
                workContext,
                taxModelFactory,
                taxPluginManager,
                taxSettings)
        {
            _avalaraTaxManager = avalaraTaxManager;
            _genericAttributeService = genericAttributeService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _cacheManager = cacheManager;
            _taxCategoryService = taxCategoryService;
            _taxPluginManager = taxPluginManager;
        }

        #endregion

        #region Methods

        public override async Task<IActionResult> Categories()
        {
            //ensure that Avalara tax provider is active
            if (!await _taxPluginManager.IsPluginActiveAsync(AvalaraTaxDefaults.SystemName))
            {
                //if isn't active return base action result
                RouteData.Values["controller"] = "Tax";
                return await base.Categories();
            }

            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //prepare model
            var model = new Models.Tax.TaxCategorySearchModel();
            var cacheKey = _cacheManager.PrepareKeyForDefaultCache(AvalaraTaxDefaults.TaxCodeTypesCacheKey);
            var taxCodeTypes = await _cacheManager.GetAsync(cacheKey, async () => await _avalaraTaxManager.GetTaxCodeTypesAsync());

            if (taxCodeTypes != null)
                model.AvailableTypes = taxCodeTypes.Select(type => new SelectListItem(type.Value, type.Key)).ToList();
            model.SetGridPageSize();

            //use overridden view
            return View("~/Plugins/Tax.Avalara/Views/Tax/Categories.cshtml", model);
        }

        [HttpPost]
        public override async Task<IActionResult> Categories(TaxCategorySearchModel searchModel)
        {
            //ensure that Avalara tax provider is active
            if (!await _taxPluginManager.IsPluginActiveAsync(AvalaraTaxDefaults.SystemName))
                return await base.Categories(searchModel);

            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageTaxSettings))
                return await AccessDeniedDataTablesJson();

            //get tax categories
            var taxCategories = (await _taxCategoryService.GetAllTaxCategoriesAsync()).ToPagedList(searchModel);

            //get tax types and define the default value
            var cacheKey = _cacheManager.PrepareKeyForDefaultCache(AvalaraTaxDefaults.TaxCodeTypesCacheKey);
            var taxTypes = (await _cacheManager.GetAsync(cacheKey, async () => await _avalaraTaxManager.GetTaxCodeTypesAsync()))
                ?.Select(taxType => new { Id = taxType.Key, Name = taxType.Value });
            var defaultType = taxTypes
                ?.FirstOrDefault(taxType => taxType.Name.Equals("Unknown", StringComparison.InvariantCultureIgnoreCase))
                ?? taxTypes?.FirstOrDefault();

            //prepare grid model
            var model = await new Models.Tax.TaxCategoryListModel().PrepareToGridAsync(searchModel, taxCategories, () =>
            {
                //fill in model values from the entity
                return taxCategories.SelectAwait(async taxCategory =>
                {
                    //fill in model values from the entity
                    var taxCategoryModel = new Models.Tax.TaxCategoryModel
                    {
                        Id = taxCategory.Id,
                        Name = taxCategory.Name,
                        DisplayOrder = taxCategory.DisplayOrder
                    };

                    //try to get previously saved tax code type and description
                    var taxCodeType = (await taxTypes?.FirstOrDefaultAwaitAsync(async type =>
                        type.Id.Equals((await _genericAttributeService.GetAttributeAsync<string>(taxCategory, AvalaraTaxDefaults.TaxCodeTypeAttribute)) ?? string.Empty)))
                        ?? defaultType;
                    taxCategoryModel.Type = taxCodeType?.Name ?? string.Empty;
                    taxCategoryModel.TypeId = taxCodeType?.Id ?? Guid.Empty.ToString();
                    taxCategoryModel.Description = (await _genericAttributeService
                        .GetAttributeAsync<string>(taxCategory, AvalaraTaxDefaults.TaxCodeDescriptionAttribute)) ?? string.Empty;

                    return taxCategoryModel;
                });
            });

            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> TaxCategoryUpdate(Models.Tax.TaxCategoryModel model)
        {
            return await base.CategoryUpdate(model);
        }

        [HttpPost]
        public async Task<IActionResult> TaxCategoryAdd(Models.Tax.TaxCategoryModel model)
        {
            //ensure that Avalara tax provider is active
            if (!await _taxPluginManager.IsPluginActiveAsync(AvalaraTaxDefaults.SystemName))
                return new NullJsonResult();

            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return ErrorJson(ModelState.SerializeErrors());

            var taxCategory = new TaxCategory();
            taxCategory = model.ToEntity(taxCategory);
            await _taxCategoryService.InsertTaxCategoryAsync(taxCategory);

            //save tax code type as generic attribute
            if (!string.IsNullOrEmpty(model.TypeId) && !model.TypeId.Equals(Guid.Empty.ToString()))
                await _genericAttributeService.SaveAttributeAsync(taxCategory, AvalaraTaxDefaults.TaxCodeTypeAttribute, model.TypeId);

            return Json(new { Result = true });
        }

        [HttpPost]
        public override async Task<IActionResult> CategoryDelete(int id)
        {
            //ensure that Avalara tax provider is active
            if (!await _taxPluginManager.IsPluginActiveAsync(AvalaraTaxDefaults.SystemName))
                return new NullJsonResult();

            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //try to get a tax category with the specified id
            var taxCategory = await _taxCategoryService.GetTaxCategoryByIdAsync(id);
            if (taxCategory == null)
                throw new ArgumentException("No tax category found with the specified id");

            //delete generic attributes 
            await _genericAttributeService.SaveAttributeAsync<string>(taxCategory, AvalaraTaxDefaults.TaxCodeDescriptionAttribute, null);
            await _genericAttributeService.SaveAttributeAsync<string>(taxCategory, AvalaraTaxDefaults.TaxCodeTypeAttribute, null);

            await _taxCategoryService.DeleteTaxCategoryAsync(taxCategory);

            return new NullJsonResult();
        }

        [HttpPost, ActionName("Categories")]
        [FormValueRequired("importTaxCodes")]
        public async Task<IActionResult> ImportTaxCodes()
        {
            //ensure that Avalara tax provider is active
            if (!await _taxPluginManager.IsPluginActiveAsync(AvalaraTaxDefaults.SystemName))
                return await Categories();

            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageTaxSettings))
                return AccessDeniedView();

            //import tax caodes
            var importedTaxCodesNumber = await _avalaraTaxManager.ImportTaxCodesAsync();
            if (importedTaxCodesNumber.HasValue)
            {
                //successfully imported

nopCommerce_4.40.3_Source/src/Plugins/Nop.Plugin.Tax.Avalara/Views/Tax/Categories.cshtml
@model TaxCategorySearchModel

@{
    Layout = "_AdminLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Configuration.Tax.Categories").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Tax categories");
}

<form asp-controller="AvalaraTax" asp-action="Categories" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Tax.Categories")
        </h1>
        <div class="float-right">
            <div class="btn-group">
                <button type="button" class="btn btn-warning">
                    <i class="fas fa-exchange-alt"></i>
                    @T("Plugins.Tax.Avalara.TaxCodes")
                </button>
                <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">&nbsp;</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <button type="submit" name="exportTaxCodes">
                            <i class="fas fa-exchange-alt"></i>
                            @T("Plugins.Tax.Avalara.TaxCodes.Export")
                        </button>
                    </li>
                    <li>
                        <button type="submit" name="importTaxCodes">
                            <i class="fas fa-exchange-alt"></i>
                            @T("Plugins.Tax.Avalara.TaxCodes.Import")
                        </button>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <button type="submit" name="deleteTaxCodes">
                            <i class="far fa-trash-alt"></i>
                            @T("Plugins.Tax.Avalara.TaxCodes.Delete")
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <div class="cards-group">
                    @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.TaxCategoryListButtons })
                    <div class="card card-default">
                        <div class="card-body">
                            @await Html.PartialAsync("Table", new DataTablesModel
                            {
                                Name = "tax-categories-grid",
                                UrlRead = new DataUrl("Categories", "AvalaraTax", null),
                                UrlDelete = new DataUrl("CategoryDelete", "AvalaraTax", null),
                                UrlUpdate = new DataUrl("TaxCategoryUpdate", "AvalaraTax", null),
                                Length = Model.PageSize,
                                LengthMenu = Model.AvailablePageSizes,
                                ColumnCollection = new List<ColumnProperty>
                                {
                                    new ColumnProperty(nameof(TaxCategoryModel.Name))
                                    {
                                        Title = T("Admin.Configuration.Tax.Categories.Fields.Name").Text,
                                        Width = "300",
                                        Editable = true,
                                        EditType = EditType.String
                                    },
                                    new ColumnProperty(nameof(TaxCategoryModel.DisplayOrder))
                                    {
                                        Title = T("Admin.Configuration.Tax.Categories.Fields.DisplayOrder").Text,
                                        Width = "100",
                                        ClassName = NopColumnClassDefaults.CenterAll,
                                        Editable = true,
                                        EditType = EditType.Number
                                    },
                                    new ColumnProperty(nameof(TaxCategoryModel.Type))
                                    {
                                        Title = T("Plugins.Tax.Avalara.Fields.TaxCodeType").Text,
                                        Width = "100",
                                        ClassName = NopColumnClassDefaults.CenterAll
                                    },
                                    new ColumnProperty(nameof(TaxCategoryModel.Description))
                                    {
                                        Title = T("Plugins.Tax.Avalara.Fields.TaxCodeDescription").Text
                                    },
                                    new ColumnProperty(nameof(TaxCategoryModel.Id))
                                    {
                                        Title = T("Admin.Common.Edit").Text,
                                        Width = "100",
                                        ClassName = NopColumnClassDefaults.Button,
                                        Render = new RenderButtonsInlineEdit()
                                    },
                                    new ColumnProperty(nameof(TaxCategoryModel.Id))
                                    {
                                        Title = T("Admin.Common.Delete").Text,
                                        Width = "100",
                                        Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                                        ClassName = NopColumnClassDefaults.Button
                                    }
                                }
                            })

                            <div class="card card-default">
                                <div class="card-header">
                                    @T("Admin.Common.AddNewRecord")
                                </div>
                                <div class="card-body">
                                    <div class="form-group row">
                                        <div class="col-md-3">
                                            <nop-label asp-for="@Model.AddTaxCategory.Name" />
                                        </div>
                                        <div class="col-md-9">
                                            <nop-editor asp-for="@Model.AddTaxCategory.Name" />
                                            <span asp-validation-for="@Model.AddTaxCategory.Name"></span>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-3">
                                            <nop-label asp-for="@Model.AddTaxCategory.DisplayOrder" />
                                        </div>
                                        <div class="col-md-9">
                                            <nop-editor asp-for="@Model.AddTaxCategory.DisplayOrder" />
                                            <span asp-validation-for="@Model.AddTaxCategory.DisplayOrder"></span>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-3">
                                            <nop-label asp-for="@Model.AddTaxCategory.TypeId" />
                                        </div>
                                        <div class="col-md-9">
                                            <nop-select asp-for="@Model.AddTaxCategory.TypeId" asp-items="@Model.AvailableTypes" />
                                            <span asp-validation-for="@Model.AddTaxCategory.TypeId"></span>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-9 offset-md-3">
                                            <button type="button" id="addTaxCategory" class="btn btn-primary">@T("Admin.Common.AddNewRecord")</button>
                                        </div>
                                    </div>
                                </div>
                                <script>
                                    $(document).ready(function () {
                                        $('#addTaxCategory').click(function () {
                                            $('#addTaxCategory').attr('disabled', true);
                                            var postData = {
                                                Name: $("#@Html.IdFor(model => model.AddTaxCategory.Name)").val(),
                                                DisplayOrder: $("#@Html.IdFor(model => model.AddTaxCategory.DisplayOrder)").val(),
                                                TypeId: $("#@Html.IdFor(model => model.AddTaxCategory.TypeId)").val()
                                            };
                                            addAntiForgeryToken(postData);

                                            $.ajax({
                                                cache: false,
                                                type: "POST",
                                                url: "@Html.Raw(Url.Action("TaxCategoryAdd", "AvalaraTax", null))",
                                                data: postData,
                                                success: function (data, textStatus, jqXHR) {
                                                    if (data.Result) {
                                                        updateTable('#tax-categories-grid');
                                                        $("#@Html.IdFor(model => model.AddTaxCategory.Name)").val('');
                                                        $("#@Html.IdFor(model => model.AddTaxCategory.DisplayOrder)").data("kendoNumericTextBox").value(0);
                                                        $("#@Html.IdFor(model => model.AddTaxCategory.TypeId)").val('');
                                                    } else {
                                                        display_nop_error(data);
                                                    }
                                                },
                                                complete: function (jqXHR, textStatus) {
                                                    $('#addTaxCategory').attr('disabled', false);
                                                }
                                            });
                                        });
                                    });
                                </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>